### ISSUE TITLE
Cannot install via composer php 7.4

### ISSUE THREAD

**Issue by oim37** [wintercms/wn-ckeditor-plugin#1]
Hello,

Have error   Could not parse version constraint wn-ckeditor-plugin: Invalid version string "wn-ckeditor-plugin"  
when use composer to install plugin.

Other plugins installed succesfuly:
Using version ^2.0 for winter/wn-builder-plugin
Using version ^2.1 for winter/wn-translate-plugin
Using version ^2.0 for winter/wn-sitemap-plugin
Using version ^2.0 for winter/wn-pages-plugin

May be i need set another verison

**Comment by LukeTowers** [comment]
It wasn't added to packagist yet, I've added it now so it should be available: https://packagist.org/packages/winter/wn-ckeditor-plugin
