### ISSUE TITLE
How activate?

### ISSUE THREAD

**Issue by oim37** [wintercms/wn-ckeditor-plugin#2]
I install plugin and want to change default to this. In settings not found options to activate.

I don't know how to activate

**Comment by bennothommo** [comment]
@oim37 this plugin provides CKEditor as an alternative, not as a replacement to the Froala editor. If you want to replace any instances of Froala with the CKEditor, you will need to use an event like `backend.form.extendFields` to change the richeditor fields to CKEditor fields.

This Winter trick by @mjauvin shows an example of doing this for the Winter.Blog blog content field:
https://wintertricks.com/tricks/use-a-rich-editor-form-widget-as-the-winterblog-post-editor

**Comment by LukeTowers** [comment]
The original CKEditor plugin this is loosely based off of did automatically swap out the richeditor type to ckeeditor with some options, so I do plan on adding that as an option at some point but I'm not working on this plugin at the moment, so in the meantime @bennothommo's solution is the correct one.

**Comment by oim37** [comment]
Thank you for answer.

If i change $widget->secondaryTabs['fields']['content']['type'] = 'richeditor'; 
to 
$widget->secondaryTabs['fields']['content']['type'] = 'ckeditor'; 

i have error "partial with name _ckeditor.htm" not found.

For test i change richeditor to codeeditor 
$widget->secondaryTabs['fields']['content']['type'] = 'codeeditor'; 
and it working.

What I doing wrong?
in files i see only _ckeditor.php https://github.com/wintercms/wn-ckeditor-plugin/tree/main/formwidgets/ckeditor/partials

**Comment by oim37** [comment]
I think this error, because i have php 7.4 and 1.1.10 version, but now i can't update to php 8.* 
May be have some fast solution or no?

**Comment by oim37** [comment]
I update to php 8 and 1.2.1, update ok, error now not showing.

On category blog tab showing category, on editor tab all empty without any buttons and text field.

**Comment by jirkasim3** [comment]
I had the same problem so i researched and found that ckeditor can't find plugins.
You can try my [repository](https://github.com/jirkasim3/wn-ckeditor-plugin). Here you can find my working configuration.

Currently I was forced to put all the plugins locally because the CDN doesn't have them. Unfortunately, I couldn't find any other plugins that needed it, so I was forced to disable them. It has one disadvantage and that is that there are many small files and it takes time to upload them.

I will try to find a better solution.

**Comment by bennothommo** [comment]
@oim37 are there any JavaScript errors being thrown in the Developer Console of your browser?

**Comment by oim37** [comment]
> @oim37 are there any JavaScript errors being thrown in the Developer Console of your browser?

Yes, 

Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "mediamanager" was not found at "https://cdn.ckeditor.com/4.20.0/standard-all/plugins/mediamanager/plugin.js?t=M8SB".
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.resourceManager.<anonymous> (ckeditor.js:253:450)
    at n (ckeditor.js:249:123)
    at Array.v (ckeditor.js:249:266)
    at w (ckeditor.js:249:350)
    at CKEDITOR.env.ie.g.$.onerror (ckeditor.js:250:354)

**Comment by bennothommo** [comment]
@oim37 it seems to be loading up a plugin that doesn't exist - I think we have our own `mediamanager` CKEditor plugin within this repo. @LukeTowers might know more about that?

**Comment by LukeTowers** [comment]
It might not be functional yet, I don't know if I finished working on this plugin or not yet TBH
